# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  DEPOT_TOOLS_WIN_TOOLCHAIN: 0
  GYP_MSVS_VERSION: 2017

pool:
  vmImage: 'windows-latest'

steps:
- script: v8_ci.bat nopause
  displayName: 'build v8'